[package]
authors = ["TERRAPEXC Labs"]
description = "Common terrapexc types"
documentation = "https://docs.terrapexc.io"
edition = "2021"
homepage = "https://terrapexc.com"
license = "Apache-2.0"
name = "classic_terrapexc"
repository = "https://github.com/terrapexc"
version = "2.6.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = {version = "0.16.7"}
cosmwasm-storage = {version = "0.16.0"}
cw-storage-plus = {version = "0.8.0"}
cw20 = {version = "0.8.0"}
protobuf = {version = "2", features = ["with-bytes"]}
schemars = "0.8.1"
serde = {version = "1.0.103", default-features = false, features = ["derive"]}
serde_json = {version = "1.0"}
terra-cosmwasm = {version = "2.2.0"}

[dev-dependencies]
cosmwasm-schema = "0.16.0"

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = true
panic = 'abort'
rpath = false
