name = "terrapexc-router"
version = "0.1.0"
authors = ["TERRAPEXC Labs."]
edition = "2021"
description = "A Terrapexc router contract - provides multi-step operations to facilitate single sign operation"
license = "Apache-2.0"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "0.8.0" } 
cosmwasm-std = { version = "0.16.7" }
classic_terrapexc = { path = "../../packages/classic_terrapexc", version = "2.6.1" }
terra-cosmwasm = "2.2.0"
cw-storage-plus = { version = "0.8.0"}
integer-sqrt = "0.1.5"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
cosmwasm-bignumber = "2.2.0"
cw2 = { version = "0.8.0" } 

[dev-dependencies]
cosmwasm-storage = { version = "0.16.0" }
cosmwasm-schema = "0.16.0"
